baseurl = "/"
languageCode = "en-us"
title = "Globetrotting with Muscular Dystrophy"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/adivea/DisabledinDenmark"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/adivea"
[[menu.main]]
    name = "Posts"
    pre = "fa-bullhorn"
    url = "/post/"
    weight = 4

[params]
    description = "Adela and Vivienne's site."
    chapter = "Aarhus, June 2020"
    customCSS = ["css/erum.css", "css/font-awesome.min.css"]

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

